name: Maschinendeck
url: http://www.maschinendeck.org
description: Hacker, Maker & Nerd Space in Trier, Germany

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
